using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddOpenApi();
builder.Services.AddDbContext<IdentityDbContext>(options => options.UseNpgsql(builder.Configuration.GetConnectionString("IdentityDb")));
builder.Services.AddSingleton<IPasswordHasher<UserEntity>, PasswordHasher<UserEntity>>();
var jwtSecret = builder.Configuration["Jwt:Secret"] ?? throw new InvalidOperationException("Jwt:Secret must be configured."); var jwtIssuer = builder.Configuration["Jwt:Issuer"] ?? "enterprise-ecommerce"; var jwtAudience = builder.Configuration["Jwt:Audience"] ?? "enterprise-ecommerce-web";
builder.Services.AddAuthentication().AddJwtBearer(options => options.TokenValidationParameters = new TokenValidationParameters { ValidateIssuer = true, ValidateAudience = true, ValidateLifetime = true, ValidateIssuerSigningKey = true, ValidIssuer = jwtIssuer, ValidAudience = jwtAudience, IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtSecret)) }); builder.Services.AddAuthorization();
var app = builder.Build(); await using (var scope = app.Services.CreateAsyncScope()) await scope.ServiceProvider.GetRequiredService<IdentityDbContext>().Database.MigrateAsync(); app.UseAuthentication(); app.UseAuthorization(); app.MapOpenApi();
app.MapGet("/health", () => Results.Ok(new { status = "healthy", service = "identity" }));
app.MapPost("/api/v1/auth/register", async (RegisterRequest request, IdentityDbContext db, IPasswordHasher<UserEntity> hasher, CancellationToken cancellationToken) => { if (await db.Users.AnyAsync(user => user.Email == request.Email.Trim().ToLowerInvariant(), cancellationToken)) return Results.Conflict(new { error = "Email is already registered." }); var user = new UserEntity { Id = Guid.NewGuid(), Email = request.Email.Trim().ToLowerInvariant(), DisplayName = request.DisplayName.Trim(), Role = "Customer", IsActive = true }; user.PasswordHash = hasher.HashPassword(user, request.Password); db.Users.Add(user); await db.SaveChangesAsync(cancellationToken); return Results.Created($"/api/v1/users/{user.Id}", new { user.Id, user.Email, user.DisplayName, user.Role }); });
app.MapPost("/api/v1/auth/login", async (LoginRequest request, IdentityDbContext db, IPasswordHasher<UserEntity> hasher, CancellationToken cancellationToken) => { var user = await db.Users.SingleOrDefaultAsync(item => item.Email == request.Email.Trim().ToLowerInvariant(), cancellationToken); if (user is null || !user.IsActive || hasher.VerifyHashedPassword(user, user.PasswordHash, request.Password) == PasswordVerificationResult.Failed) return Results.Unauthorized(); return Results.Ok(await TokenService.IssueAsync(user, db, jwtSecret, jwtIssuer, jwtAudience, cancellationToken)); });
app.MapPost("/api/v1/auth/refresh", async (RefreshRequest request, IdentityDbContext db, CancellationToken cancellationToken) => { var hash = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(request.RefreshToken))); var token = await db.RefreshTokens.Include(item => item.User).SingleOrDefaultAsync(item => item.TokenHash == hash && item.ExpiresAt > DateTimeOffset.UtcNow && item.RevokedAt == null, cancellationToken); if (token is null) return Results.Unauthorized(); token.RevokedAt = DateTimeOffset.UtcNow; await db.SaveChangesAsync(cancellationToken); return Results.Ok(await TokenService.IssueAsync(token.User, db, jwtSecret, jwtIssuer, jwtAudience, cancellationToken)); });
app.MapGet("/api/v1/profile", (ClaimsPrincipal user) => Results.Ok(new { id = user.FindFirstValue(JwtRegisteredClaimNames.Sub), email = user.FindFirstValue(ClaimTypes.Email), role = user.FindFirstValue(ClaimTypes.Role) })).RequireAuthorization();
app.Run();
public sealed record RegisterRequest(string Email, string Password, string DisplayName); public sealed record LoginRequest(string Email, string Password); public sealed record RefreshRequest(string RefreshToken);
public sealed class UserEntity { public Guid Id { get; set; } public string Email { get; set; } = string.Empty; public string DisplayName { get; set; } = string.Empty; public string Role { get; set; } = "Customer"; public bool IsActive { get; set; } public string PasswordHash { get; set; } = string.Empty; public List<RefreshTokenEntity> RefreshTokens { get; set; } = []; }
public sealed class RefreshTokenEntity { public Guid Id { get; set; } public Guid UserId { get; set; } public UserEntity User { get; set; } = null!; public string TokenHash { get; set; } = string.Empty; public DateTimeOffset ExpiresAt { get; set; } public DateTimeOffset? RevokedAt { get; set; } }
public sealed class IdentityDbContext(DbContextOptions<IdentityDbContext> options) : DbContext(options) { public DbSet<UserEntity> Users => Set<UserEntity>(); public DbSet<RefreshTokenEntity> RefreshTokens => Set<RefreshTokenEntity>(); protected override void OnModelCreating(ModelBuilder modelBuilder) { modelBuilder.Entity<UserEntity>().ToTable("users").HasKey(user => user.Id); modelBuilder.Entity<UserEntity>().HasIndex(user => user.Email).IsUnique(); modelBuilder.Entity<RefreshTokenEntity>().ToTable("refresh_tokens").HasKey(token => token.Id); modelBuilder.Entity<RefreshTokenEntity>().HasIndex(token => token.TokenHash).IsUnique(); modelBuilder.Entity<RefreshTokenEntity>().HasOne(token => token.User).WithMany(user => user.RefreshTokens).HasForeignKey(token => token.UserId); } }
public static class TokenService { public static async Task<object> IssueAsync(UserEntity user, IdentityDbContext db, string secret, string issuer, string audience, CancellationToken cancellationToken) { var claims = new[] { new Claim(JwtRegisteredClaimNames.Sub, user.Id.ToString()), new Claim(ClaimTypes.Email, user.Email), new Claim(ClaimTypes.Role, user.Role) }; var key = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(secret)); var accessToken = new JwtSecurityToken(issuer, audience, claims, expires: DateTime.UtcNow.AddMinutes(30), signingCredentials: new SigningCredentials(key, SecurityAlgorithms.HmacSha256)); var refresh = Convert.ToBase64String(RandomNumberGenerator.GetBytes(48)); db.RefreshTokens.Add(new RefreshTokenEntity { Id = Guid.NewGuid(), UserId = user.Id, TokenHash = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(refresh))), ExpiresAt = DateTimeOffset.UtcNow.AddDays(14) }); await db.SaveChangesAsync(cancellationToken); return new { accessToken = new JwtSecurityTokenHandler().WriteToken(accessToken), refreshToken = refresh, expiresIn = 1800 }; } }
public sealed class IdentityDbContextFactory : Microsoft.EntityFrameworkCore.Design.IDesignTimeDbContextFactory<IdentityDbContext> { public IdentityDbContext CreateDbContext(string[] args) => new(new DbContextOptionsBuilder<IdentityDbContext>().UseNpgsql("Host=localhost;Port=5432;Database=identity;Username=ecommerce;Password=ecommerce_dev_only").Options); }
public partial class Program;